### ISSUE TITLE
resolve the test case failure for RefRemoteValidator

### ISSUE THREAD

**Issue by stevehu** [networknt/json-schema-validator#234]
Here is the error message when running the test case in v6, v7 and v2019-09. It looks like a new id folder is added for switching the folder on the remote reference. 

```
14:37:35.472 [main] ERROR c.networknt.schema.JsonSchemaFactory - Failed to load json schema!
java.io.IOException: Resource draft6/folderInteger.json not found in classpath.
	at com.networknt.schema.uri.ClasspathURLStreamHandler$ClassPathURLConnection.getResourceAsStream(ClasspathURLStreamHandler.java:94)
	at com.networknt.schema.uri.ClasspathURLStreamHandler$ClassPathURLConnection.getInputStream(ClasspathURLStreamHandler.java:70)
	at java.net.URL.openStream(URL.java:1045)
	at com.networknt.schema.uri.ClasspathURLFetcher.fetch(ClasspathURLFetcher.java:39)
	at com.networknt.schema.uri.URISchemeFetcher.fetch(URISchemeFetcher.java:50)
	at com.networknt.schema.JsonSchemaFactory.getSchema(JsonSchemaFactory.java:322)
	at com.networknt.schema.RefValidator.getRefSchema(RefValidator.java:68)
	at com.networknt.schema.RefValidator.<init>(RefValidator.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.networknt.schema.ValidatorTypeCode.newValidator(ValidatorTypeCode.java:128)
	at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:341)
	at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:50)
	at com.networknt.schema.JsonSchema.read(JsonSchema.java:159)
	at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:76)
	at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:62)
	at com.networknt.schema.ItemsValidator.<init>(ItemsValidator.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.networknt.schema.ValidatorTypeCode.newValidator(ValidatorTypeCode.java:128)
	at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:341)
	at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:50)
	at com.networknt.schema.JsonSchema.read(JsonSchema.java:159)
	at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:76)
	at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:62)
	at com.networknt.schema.ItemsValidator.<init>(ItemsValidator.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.networknt.schema.ValidatorTypeCode.newValidator(ValidatorTypeCode.java:128)
	at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:341)
	at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:50)
	at com.networknt.schema.JsonSchema.read(JsonSchema.java:159)
	at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:76)
	at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:62)
	at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:57)
	at com.networknt.schema.JsonSchemaFactory.newJsonSchema(JsonSchemaFactory.java:253)
	at com.networknt.schema.JsonSchemaFactory.getSchema(JsonSchemaFactory.java:347)
	at com.networknt.schema.V6JsonSchemaTest.runTestFile(V6JsonSchemaTest.java:73)
	at com.networknt.schema.V6JsonSchemaTest.testRefRemoteValidator(V6JsonSchemaTest.java:293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)



java.lang.IllegalStateException: Current schema should not be invalid: draft6/refRemote.json

	at com.networknt.schema.V6JsonSchemaTest.runTestFile(V6JsonSchemaTest.java:104)
	at com.networknt.schema.V6JsonSchemaTest.testRefRemoteValidator(V6JsonSchemaTest.java:293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.networknt.schema.JsonSchemaException: java.io.IOException: Resource draft6/folderInteger.json not found in classpath.
	at com.networknt.schema.JsonSchemaFactory.getSchema(JsonSchemaFactory.java:338)
	at com.networknt.schema.RefValidator.getRefSchema(RefValidator.java:68)
	at com.networknt.schema.RefValidator.<init>(RefValidator.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.networknt.schema.ValidatorTypeCode.newValidator(ValidatorTypeCode.java:128)
	at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:341)
	at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:50)
	at com.networknt.schema.JsonSchema.read(JsonSchema.java:159)
	at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:76)
	at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:62)
	at com.networknt.schema.ItemsValidator.<init>(ItemsValidator.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.networknt.schema.ValidatorTypeCode.newValidator(ValidatorTypeCode.java:128)
	at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:341)
	at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:50)
	at com.networknt.schema.JsonSchema.read(JsonSchema.java:159)
	at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:76)
	at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:62)
	at com.networknt.schema.ItemsValidator.<init>(ItemsValidator.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.networknt.schema.ValidatorTypeCode.newValidator(ValidatorTypeCode.java:128)
	at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:341)
	at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:50)
	at com.networknt.schema.JsonSchema.read(JsonSchema.java:159)
	at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:76)
	at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:62)
	at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:57)
	at com.networknt.schema.JsonSchemaFactory.newJsonSchema(JsonSchemaFactory.java:253)
	at com.networknt.schema.JsonSchemaFactory.getSchema(JsonSchemaFactory.java:347)
	at com.networknt.schema.V6JsonSchemaTest.runTestFile(V6JsonSchemaTest.java:73)
	... 25 more
Caused by: java.io.IOException: Resource draft6/folderInteger.json not found in classpath.
	at com.networknt.schema.uri.ClasspathURLStreamHandler$ClassPathURLConnection.getResourceAsStream(ClasspathURLStreamHandler.java:94)
	at com.networknt.schema.uri.ClasspathURLStreamHandler$ClassPathURLConnection.getInputStream(ClasspathURLStreamHandler.java:70)
	at java.net.URL.openStream(URL.java:1045)
	at com.networknt.schema.uri.ClasspathURLFetcher.fetch(ClasspathURLFetcher.java:39)
	at com.networknt.schema.uri.URISchemeFetcher.fetch(URISchemeFetcher.java:50)
	at com.networknt.schema.JsonSchemaFactory.getSchema(JsonSchemaFactory.java:322)
	... 63 more



```

**Comment by fdutton** [comment]
Resolved in #697
