### ISSUE TITLE
Cyclic dependencies result in StackOverflowError

### ISSUE THREAD

**Issue by mihaiba** [networknt/json-schema-validator#258]
Having schemaA with property referencing schemaB and schemaB referencing schemaA results in StackOverflowError:
```
Caused by: com.networknt.schema.JsonSchemaException: java.lang.StackOverflowError
	at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:346)
	at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:50)
	at com.networknt.schema.JsonSchema.read(JsonSchema.java:159)
	at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:76)
	at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:62)
	at com.networknt.schema.PropertiesValidator.<init>(PropertiesValidator.java:35)
	at sun.reflect.GeneratedConstructorAccessor34.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.networknt.schema.ValidatorTypeCode.newValidator(ValidatorTypeCode.java:128)
	at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:340)
	at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:50)
	at com.networknt.schema.JsonSchema.read(JsonSchema.java:159)
	at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:76)
	at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:62)
	at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:57)
	at com.networknt.schema.JsonSchemaFactory.newJsonSchema(JsonSchemaFactory.java:253)
	at com.networknt.schema.JsonSchemaFactory.getSchema(JsonSchemaFactory.java:330)
```

**Comment by stevehu** [comment]
@mihaiba This issue has been resolved a long time ago and I am wondering if there are still edge case scenarios left. Would you be able to submit a PR with a test case to reproduce it? Thanks for raising it.

**Comment by mihaiba** [comment]
@stevehu PR !259 has the failing test. let me know if more details are needed. Test name is: CyclicDependencyTest

**Comment by stevehu** [comment]
@mihaiba In case you haven't seen the message I left in the PR, please correct the test case by merging the three JSON files together and try it again. Thanks.
