### ISSUE TITLE
NPE due to concurrency bug

### ISSUE THREAD

**Issue by Keymaster65** [networknt/json-schema-validator#392]
In high load tests, we sometimes get this bug:
java.lang.NullPointerException: null
at com.networknt.schema.JsonSchemaRef.validate(JsonSchemaRef.java:49)
at com.networknt.schema.RefValidator.validate(RefValidator.java:138)
at com.networknt.schema.JsonSchema.validate(JsonSchema.java:224)
at com.networknt.schema.AllOfValidator.validate(AllOfValidator.java:44)
at com.networknt.schema.JsonSchema.validate(JsonSchema.java:224)
at com.networknt.schema.JsonSchemaRef.validate(JsonSchemaRef.java:49)
at com.networknt.schema.RefValidator.validate(RefValidator.java:138)
at com.networknt.schema.JsonSchema.validate(JsonSchema.java:224)
at com.networknt.schema.ItemsValidator.doValidate(ItemsValidator.java:93)
at com.networknt.schema.ItemsValidator.validate(ItemsValidator.java:80)
at com.networknt.schema.JsonSchema.validate(JsonSchema.java:224)
at com.networknt.schema.PropertiesValidator.validate(PropertiesValidator.java:75)
at com.networknt.schema.JsonSchema.validate(JsonSchema.java:224)
at com.networknt.schema.JsonSchemaRef.validate(JsonSchemaRef.java:49)
at com.networknt.schema.RefValidator.validate(RefValidator.java:138)
at com.networknt.schema.JsonSchema.validate(JsonSchema.java:224)
at com.networknt.schema.AllOfValidator.validate(AllOfValidator.java:44)
at com.networknt.schema.JsonSchema.validate(JsonSchema.java:224)
at com.networknt.schema.JsonSchemaRef.validate(JsonSchemaRef.java:49)
at com.networknt.schema.RefValidator.validate(RefValidator.java:138)
at com.networknt.schema.JsonSchema.validate(JsonSchema.java:224)
at com.networknt.schema.PropertiesValidator.validate(PropertiesValidator.java:75)
at com.networknt.schema.JsonSchema.validate(JsonSchema.java:224)
at com.networknt.schema.JsonSchemaRef.validate(JsonSchemaRef.java:49)
at com.networknt.schema.RefValidator.validate(RefValidator.java:138)
at com.networknt.schema.JsonSchema.validate(JsonSchema.java:224)
at com.networknt.schema.ItemsValidator.doValidate(ItemsValidator.java:93)
at com.networknt.schema.ItemsValidator.validate(ItemsValidator.java:80)
at com.networknt.schema.JsonSchema.validate(JsonSchema.java:224)
at com.networknt.schema.PropertiesValidator.validate(PropertiesValidator.java:75)
at com.networknt.schema.JsonSchema.validate(JsonSchema.java:224)
at com.networknt.schema.BaseJsonValidator.validate(BaseJsonValidator.java:101

**Comment by Keymaster65** [comment]
I'll try to add a PR.

**Comment by stevehu** [comment]
@Keymaster65 We have another issue opened that is concurrency related. I don't know if they are the same root cause. The NPE is thrown from two different locations. Just for your reference. 

https://github.com/networknt/json-schema-validator/issues/335

**Comment by Keymaster65** [comment]
I think #335 is another bug.

**Comment by stevehu** [comment]
Thanks for the confirmation. I assume it is a different defect as the NPE is thrown from two different locations.
