### ISSUE TITLE
NullPointerException with JsonSchemaFactory

### ISSUE THREAD

**Issue by nd417** [networknt/json-schema-validator#510]
ObjectMapper objectMapper = new ObjectMapper();
				JsonSchemaFactory  schemaFactory = JsonSchemaFactory.builder(JsonSchemaFactory.getInstance(VersionFlag.V201909)).objectMapper(objectMapper).build();

generic exception occured:{}
java.lang.NullPointerException: null
        at com.networknt.schema.JsonSchemaFactory.findMetaSchemaForSchema(JsonSchemaFactory.java:283)
        at com.networknt.schema.JsonSchemaFactory.createValidationContext(JsonSchemaFactory.java:278)
        at com.networknt.schema.JsonSchemaFactory.newJsonSchema(JsonSchemaFactory.java:272)
        at com.networknt.schema.JsonSchemaFactory.getSchema(JsonSchemaFactory.java:316)
        at com.networknt.schema.JsonSchemaFactory.getSchema(JsonSchemaFactory.java:324)

**Comment by stevehu** [comment]
I couldn't reproduce it. Added a test case and you can try it yourself. Thanks.

https://github.com/networknt/json-schema-validator/blob/master/src/test/java/com/networknt/schema/Issue510Test.java
