### ISSUE TITLE
Validator Consistent OutOfMemoryError

### ISSUE THREAD

**Issue by ironluca** [networknt/json-schema-validator#549]
[ont-schema.zip](https://github.com/networknt/json-schema-validator/files/8424320/ont-schema.zip)
The validator is consistently giving OutOfMemoryError for a slightly larger file. The file and the schema is attached.

In the data file, if the 'properties' array is reduced to 4 elements, the schema validates in ~120 milliseconds.

The code used is as follows:

```
public class OntologyClassJSONValidator {
	
	private JsonSchemaFactory schemaFactory;
	
	private JsonSchema schema;
	
	public OntologyClassJSONValidator() throws Exception{
		
		schemaFactory=JsonSchemaFactory
						.builder(JsonSchemaFactory.getInstance(VersionFlag.V201909))
						.uriFetcher(new OntologyJSONSchemaResolver(), "http", "https")
						.build();
		
		schema=schemaFactory.getSchema(new URI(ONTOLOGY_CLASS_VALIDATION_SCHEMA_URI));
		
	}//constructor closing
	
	public void validate(JsonNode classDef, List<String> outValidationMessages) {
		
		try {

			long startValidation=System.currentTimeMillis();
			Set<ValidationMessage> result=schema.validate(classDef);
			long endValidation=System.currentTimeMillis();
			
			System.out.println(classDef.get("name")+" validation Time Taken :: "+(endValidation-startValidation));
			
			result.stream().forEach(v->{outValidationMessages.add(v.toString());});
			
		}catch(Exception e) {e.printStackTrace();}
		
	}//isValid closing
}
...

The stacktrace is as follows:

...
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3512)
	at java.base/java.util.Arrays.copyOf(Arrays.java:3481)
	at java.base/java.util.ArrayList.grow(ArrayList.java:237)
	at java.base/java.util.ArrayList.addAll(ArrayList.java:678)
	at com.networknt.schema.AllOfValidator.validate(AllOfValidator.java:98)
	at com.networknt.schema.JsonSchema.validate(JsonSchema.java:271)
	at com.networknt.schema.JsonSchemaRef.validate(JsonSchemaRef.java:38)
	at com.networknt.schema.RefValidator.validate(RefValidator.java:139)
	at com.networknt.schema.JsonSchema.validate(JsonSchema.java:271)
	at com.networknt.schema.ItemsValidator.doValidate(ItemsValidator.java:99)
	at com.networknt.schema.ItemsValidator.validate(ItemsValidator.java:86)
	at com.networknt.schema.JsonSchema.validate(JsonSchema.java:271)
	at com.networknt.schema.PropertiesValidator.validate(PropertiesValidator.java:68)
	at com.networknt.schema.JsonSchema.validate(JsonSchema.java:271)
	at com.networknt.schema.JsonSchema.validate(JsonSchema.java:257)
	at com.provise.platform.ont.def.validation.OntologyClassJSONValidator.validate(OntologyClassJSONValidator.java:45)
	at com.provise.platform.ont.def.validation.OntologyClassJSONValidator.main(OntologyClassJSONValidator.java:69)
```

**Comment by chrswk** [comment]
Can confirm.

Upgraded yesterday from 1.0.57 to 1.0.68 (for #509 fix) and now CI builds run out of memory and some local tests take seconds instead of ms.

**Comment by AndreasALoew** [comment]
See https://github.com/networknt/json-schema-validator/issues/546#issuecomment-1094406182 for leak confirmation and proposed fix.

**Comment by stevehu** [comment]
I am closing this issue and using the main issue to trace it.
