### ISSUE TITLE
NPE retrieving default values from schema

### ISSUE THREAD

**Issue by mbrkic-r3** [networknt/json-schema-validator#604]
Error 

```java
java.lang.NullPointerException
	at com.networknt.schema.PropertiesValidator.walk(PropertiesValidator.java:118)
	at com.networknt.schema.JsonSchema.walk(JsonSchema.java:411)
	at com.networknt.schema.PropertiesValidator.walkSchema(PropertiesValidator.java:163)
	at com.networknt.schema.PropertiesValidator.walk(PropertiesValidator.java:126)
	at com.networknt.schema.JsonSchema.walk(JsonSchema.java:411)
	at com.networknt.schema.JsonSchema.walk(JsonSchema.java:374)
...
```

can be reproduced with:

```java
package com.networknt.schema;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

public class IssueTest {
    @Test
    public void failure() {
        SchemaValidatorsConfig config = new SchemaValidatorsConfig();
        config.setApplyDefaultsStrategy(new ApplyDefaultsStrategy(true, false, false));
        JsonSchemaFactory factory = JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V7);
        JsonSchema schema = factory.getSchema("{ \"type\": \"object\", \"properties\": { \"foo\": { \"type\": \"object\", \"properties\": { \"bar\": { \"type\": \"boolean\", \"default\": false } } } } }", config);
        ObjectMapper objectMapper = new ObjectMapper();
        assertDoesNotThrow(() -> {
            schema.walk(objectMapper.readTree("{}"), false);
        });
    }
}

```

**Comment by stevehu** [comment]
@mbrkic-r3 I have reproduced this issue. We have an NPE because the input node is null in the second level when the walker is trying to walk the foo. The input parent is an empty map, and there is foo inside. Fixing the NPE is very easy; however, we must define the correct behaviour for this scenario. Should we add a validation error in this case? or just stop walking blindly? @prashanthjos what do you think?

**Comment by fdutton** [comment]
@stevehu I think we should simply stop walking. `foo` is not a required property in the scenario and if it were, we get that validation error.
