### ISSUE TITLE
i18n Bundle not found

### ISSUE THREAD

**Issue by MarcelloModica** [networknt/json-schema-validator#630]
![image](https://user-images.githubusercontent.com/6474548/211223762-143bdb9b-738e-42dd-9a41-b477f3ce87a8.png)

I have this error after i build a mative-image with GraalVM and launch it on linux. Seem that maven is not load and package some Bundle files. . Can you help me?

This is the stack trace:

```

4.97MB for 190 more packages                                1.99MB for 1123 more object types
------------------------------------------------------------------------------------------------------------------------
                        2.0s (2.0% of total time) in 24 GCs | Peak RSS: 2.72GB | CPU load: 1.97
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /home/runner/work/acy_cli/acy_cli/acy-cli (executable)
 /home/runner/work/acy_cli/acy_cli/acy-cli.build_artifacts.txt (txt)
 /tmp/native-image-build-output.json (json)
========================================================================================================================
Finished generating 'acy-cli' in 1m 36s.
Accyourate Group Spa CLI - Copyright 2022 -  Developed by LOGCONSULTING - oneclickapp.it
Trying to get JSON schema for validation from URL : https://raw.githubusercontent.com/Accyourate-Group-S-p-A/acy_bom/main/schema/streams/acy.schema.json
java.util.MissingResourceException: Can't find bundle for base name jsv-messages, locale en
Trying to get JSON payload to validate from URL : https://raw.githubusercontent.com/Accyourate-Group-S-p-A/acy_bom/main/schema/streams/test/ecg.json
	at java.base@17.0.5/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2045)
	at java.base@17.0.5/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1683)
	at java.base@17.0.5/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1586)
	at java.base@17.0.5/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1549)
	at java.base@17.0.5/java.util.ResourceBundle.getBundle(ResourceBundle.java:858)
	at com.networknt.schema.I18nSupport.<clinit>(I18nSupport.java:19)
	at com.networknt.schema.ValidatorTypeCode.<clinit>(ValidatorTypeCode.java:51)
	at com.networknt.schema.Version20[190](https://github.com/Accyourate-Group-S-p-A/acy_cli/actions/runs/3869307137/jobs/6595321517#step:5:191)9.getInstance(Version[201](https://github.com/Accyourate-Group-S-p-A/acy_cli/actions/runs/3869307137/jobs/6595321517#step:5:202)909.java:18)
	at com.networknt.schema.JsonSchemaFactory.getInstance(JsonSchemaFactory.java:244)
	at com.accyourate.ValidateSchema.isValid(AcyCLI.java:81)
	at com.accyourate.ValidateSchema.run(AcyCLI.java:73)
	at picocli.CommandLine.executeUserObject(CommandLine.java:[202](https://github.com/Accyourate-Group-S-p-A/acy_cli/actions/runs/3869307137/jobs/6595321517#step:5:203)6)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at com.accyourate.AcyCLI.main(AcyCLI.java:57)
Error: Process completed with exit code 1.
```

**Comment by MarcelloModica** [comment]
IF you use native-image you have to specify bundle and poperties with option 
-H:IncludeResources='(.*properties$)|(.*json$)'

**Comment by stevehu** [comment]
@MarcelloModica Thanks a lot for your help.
