### ISSUE TITLE
Unable to validate using Jackson JsonNode

### ISSUE THREAD

**Issue by MarcelloModica** [networknt/json-schema-validator#631]
![image](https://user-images.githubusercontent.com/6474548/211231375-df030730-7116-4973-9eba-bd2ef7bff11c.png)

```
`[main] WARN com.networknt.schema.JsonMetaSchema - Could not load validator type
com.networknt.schema.JsonSchemaException: java.lang.NoSuchMethodException: com.networknt.schema.TypeValidator.<init>(java.lang.String, com.fasterxml.jackson.databind.JsonNode, com.networknt.schema.JsonSchema, com.networknt.schema.ValidationContext)
	at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:299)
	at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:57)
	at com.networknt.schema.JsonSchema.read(JsonSchema.java:236)
	at com.networknt.schema.JsonSchema.getValidators(JsonSchema.java:524)
	at com.networknt.schema.JsonSchema.validate(JsonSchema.java:315)
	at com.networknt.schema.JsonSchema.validate(JsonSchema.java:299)
	at com.accyourate.ValidateSchema.isValid(AcyCLI.java:85)
	at com.accyourate.ValidateSchema.run(AcyCLI.java:73)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at com.accyourate.AcyCLI.main(AcyCLI.java:57)
Caused by: java.lang.NoSuchMethodException: com.networknt.schema.TypeValidator.<init>(java.lang.String, com.fasterxml.jackson.databind.JsonNode, com.networknt.schema.JsonSchema, com.networknt.schema.ValidationContext)
	at java.base@17.0.5/java.lang.Class.getConstructor0(DynamicHub.java:3585)
	at java.base@17.0.5/java.lang.Class.getConstructor(DynamicHub.java:2271)
	at com.networknt.schema.ValidatorTypeCode.newValidator(ValidatorTypeCode.java:156)
	at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:286)
	... 16 more
Error: Process completed with exit code 1.`
```

This is my code
```
 private boolean isValid() throws IOException {
        JsonSchemaFactory factory = JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V201909);
        JsonSchema jsonSchema = factory.getSchema(schemaUrl);
        ObjectMapper mapper = new ObjectMapper();
        JsonNode jsonNode = mapper.readTree(AcyCLI.payloadUrl.toURL());
        Set<ValidationMessage> errors = jsonSchema.validate(jsonNode);
        if (!errors.isEmpty()) {
            errors.forEach(validationMessage -> System.out.println(validationMessage.getMessage()));
            return false;
        }
        System.out.println("SCHEMA IS VALID");
        return true;
    }
```

**Comment by stevehu** [comment]
The validate method accepts the Jackson JsonNode object, and I use it constantly. It might be something else that caused the error.
