### ISSUE TITLE
Unexpected behavior when upgrading from 1.0.76 to 1.0.82

### ISSUE THREAD

**Issue by dan-s1** [networknt/json-schema-validator#853]
I have contrived example based on a similar schema which validated in version 1.0.76 yet fails validation in version 1.0.82.
I used [jackson-module-jsonSchema](https://github.com/FasterXML/jackson-module-jsonSchema) to generate a schema which is clearly v3 as stated on their github README.m yet I was able to validate this using Version flag `Draft 2020-12` on version 1.0.76 yet on 1.0.82 it fails with the the following stacktrace

```
com.networknt.schema.JsonSchemaException: java.lang.UnsupportedOperationException: No suitable validator for id
	at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:299)
	at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:57)
	at com.networknt.schema.JsonSchema.read(JsonSchema.java:236)
	at com.networknt.schema.JsonSchema.getValidators(JsonSchema.java:524)
	at com.networknt.schema.JsonSchema.validate(JsonSchema.java:315)
	at com.networknt.schema.JsonSchema.validate(JsonSchema.java:299)
```
Below are my contrived schema and sample data

Schema
```
{
  "type": "array",
  "items": {
    "type": "object",
    "id": "urn:jsonschema:com:example:Person",
    "properties": {
      "name": {
        "type": "string"
      },
      "age": {
        "type": "integer"
      },
      "courses": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "address": {
        "type": "object",
        "id": "urn:jsonschema:com:example:Address",
        "properties": {
          "firstLine": {
            "type": "string"
          },
          "secondLine": {
            "type": "string"
          },
          "thirdLine": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

Data
```
[ {
  "name" : "Jon Doe",
  "age" : 19,
  "courses" : [ "Math", "Science" ],
  "address" : {
    "firstLine" : "Jon Doe",
    "secondLine" : "101 Fairy Lane",
    "thirdLine" : "Seattle, WA 012345"
  }
}, {
  "name" : "Jane Doe",
  "age" : 19,
  "courses" : [ "Math", "Science" ],
  "address" : {
    "firstLine" : "Jon Doe",
    "secondLine" : "101 Fairy Lane",
    "thirdLine" : "Seattle, WA 012345"
  }
} ]
```

**Comment by stevehu** [comment]
You are using the 2020-12 version, and it doesn't have "id" as a keyword but "$id". https://json-schema.org/draft/2020-12/json-schema-core.html#section-8.2.1

**Comment by dan-s1** [comment]
Right but why did it work then in 1.0.76 even though it had "id" ?

**Comment by stevehu** [comment]
It was a defect, and we fixed it in the newer version.
