### ISSUE TITLE
Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')

### ISSUE THREAD

**Issue by xpagesbeast** [networknt/json-schema-validator#87]
I'm getting the same symptoms.  Is there a way to check or get the response to view the error? Some best practices?

```
[0AF4:000A-1154] 05/03/2018 09:33:19 AM  HTTP JVM: Caused by: 
[0AF4:000A-1154] 05/03/2018 09:33:19 AM  HTTP JVM: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
[0AF4:000A-1154] 05/03/2018 09:33:19 AM  HTTP JVM:  at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@2a19861e; line: 1, column: 2]
[0AF4:000A-1154] 05/03/2018 09:33:19 AM  HTTP JVM:  at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1524)
[0AF4:000A-1154] 05/03/2018 09:33:19 AM  HTTP JVM:  at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:557)
[0AF4:000A-1154] 05/03/2018 09:33:19 AM  HTTP JVM:  at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:475)
[0AF4:000A-1154] 05/03/2018 09:33:19 AM  HTTP JVM:  at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2343)
[0AF4:000A-1154] 05/03/2018 09:33:19 AM  HTTP JVM:  at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:818)
[0AF4:000A-1154] 05/03/2018 09:33:19 AM  HTTP JVM:  at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:698)
[0AF4:000A-1154] 05/03/2018 09:33:19 AM  HTTP JVM:  at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3031)
[0AF4:000A-1154] 05/03/2018 09:33:19 AM  HTTP JVM:  at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2978)
[0AF4:000A-1154] 05/03/2018 09:33:19 AM  HTTP JVM:  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2158)
[0AF4:000A-1154] 05/03/2018 09:33:19 AM  HTTP JVM:  at org.springframework.http.converter.json.MappingJackson2HttpMessageConverter.readJavaType(MappingJackson2HttpMessageConverter.java:225)
```

```
import org.springframework.web.client.RestTemplate;

public static RestTemplate getRestTemplate() {
		RestTemplate restTemplate = new RestTemplate();
		List<HttpMessageConverter<?>> messageConverters = new ArrayList<HttpMessageConverter<?>>();
		MappingJackson2HttpMessageConverter converter = new MappingJackson2HttpMessageConverter();
		List<MediaType> mediaTypes = new ArrayList<MediaType>();
		mediaTypes.add(MediaType.TEXT_HTML);
		mediaTypes.add(MediaType.APPLICATION_JSON);
		converter.setSupportedMediaTypes(mediaTypes);
		messageConverters.add(converter);
		messageConverters.add(new StringHttpMessageConverter());
		restTemplate.setMessageConverters(messageConverters);
		return restTemplate;
	}

//The call is here
ResponseEntity<BargeType[]> responseEntity = getRestTemplate().getForEntity(url+"/bargetype", BargeType[].class);

```

I checked the URL being passed in with my browser and I am getting back JSON.  I copy and pasted the response into json lint and validated it successfully.

I'm guessing there is an error returned because the error messsage has '<' in the exception.

My questions are:

1) Is there a better pattern to use RestTemplate?
2) Is there a way to get the http error?

**Comment by xpagesbeast** [comment]
posted into the wrong repository, sorry.
