### ISSUE TITLE
walk fails with validation and unevaluatedProperties

### ISSUE THREAD

**Issue by holgpar** [networknt/json-schema-validator#877]
Hi,

I wanted to walk and validate the following schema:

```json
{
  "type": "object",
  "unevaluatedProperties": false
}
```

like so:

```java

  @Test
  void walkWith__unevaluatedProperties() throws JsonProcessingException {
    JsonSchema test = getJsonSchemaFromClasspath("schemas/unevaluated.json");
    JsonNode probe = mapper.readTree("{}");

    // THIS WORKS
    test.walk(probe, false);
    test.validate(probe);

    // THIS FAILS
    test.walk(probe, true);
  }

```

However, this fails with an NPE:

```
java.lang.NullPointerException: Cannot invoke "com.networknt.schema.CollectorContext$Scope.getContainingSchema()" because "parent" is null

	at com.networknt.schema.CollectorContext.enterDynamicScope(CollectorContext.java:85)
	at com.networknt.schema.CollectorContext.enterDynamicScope(CollectorContext.java:74)
	at com.networknt.schema.UnevaluatedPropertiesValidator.validate(UnevaluatedPropertiesValidator.java:83)
	at com.networknt.schema.BaseJsonValidator.walk(BaseJsonValidator.java:200)
	at com.networknt.schema.JsonSchema.lambda$walk$1(JsonSchema.java:544)
	at java.base/java.util.TreeMap.forEach(TreeMap.java:1002)
	at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1505)
	at com.networknt.schema.JsonSchema.walk(JsonSchema.java:531)
	at com.networknt.schema.JsonSchema.walkAtNodeInternal(JsonSchema.java:511)
	at com.networknt.schema.JsonSchema.walk(JsonSchema.java:495)
	at schemas.JSONSchemaTest.walkWith__unevaluatedProperties(JSONSchemaTest.java:144)
```

**Comment by mmorys** [comment]
Have you had any resolution to this issue? I am experiencing the same :(
