### ISSUE TITLE
JsonSchemaFactory.getSchema not thread safe

### ISSUE THREAD

**Issue by mpayne-coveo** [networknt/json-schema-validator#891]
We have a service that uses the same caching mechanism/JsonSchemaFactory to load in JSON schemas, then validate against them as it handles requests in a multithreaded way. Lately, we've been seeing a lot of `ConcurrentModificationExceptions` when two requests are simultaneously handled and trying to retrieve schemas with the stack trace-
```
java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
	at com.networknt.schema.JsonSchemaFactory.findMetaSchemaForSchema(JsonSchemaFactory.java:350)
	at com.networknt.schema.JsonSchemaFactory.getSchema(JsonSchemaFactory.java:433)
	at com.networknt.schema.JsonSchemaFactory.getSchema(JsonSchemaFactory.java:462)
```
We're using version `1.0.87` of `json-schema-validator`. Let me know if you need further details

**Comment by mpayne-coveo** [comment]
The fix, I believe, should be as simple as converting `jsonMetaSchemas` from a `HashMap` to a `ConcurrentHashMap`- https://github.com/networknt/json-schema-validator/blob/e86c8174f42b462df531d81072c186e5ee7b329f/src/main/java/com/networknt/schema/JsonSchemaFactory.java#L51
