### ISSUE TITLE
Unknown Metaschema http://json-schema.org/draft-04/schema

### ISSUE THREAD

**Issue by kayvannj** [networknt/json-schema-validator#97]
We have a draft-04 schema that would would like to use in an Android project to validate jsons but as I would like to load the schema using inputstream 
```kotlin
JsonSchemaFactory.getInstance().getSchema(inputStream)
``` 

I encouter the following exception

```
    java.lang.RuntimeException: Unable to create application aaaa: com.networknt.schema.JsonSchemaException: Unknown Metaschema: http://json-schema.org/draft-04/schema
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: com.networknt.schema.JsonSchemaException: Unknown Metaschema: http://json-schema.org/draft-04/schema
        at com.networknt.schema.JsonSchemaFactory.findMetaSchemaForSchema(JsonSchemaFactory.java:157)
        at com.networknt.schema.JsonSchemaFactory.createValidationContext(JsonSchemaFactory.java:148)
        at com.networknt.schema.JsonSchemaFactory.newJsonSchema(JsonSchemaFactory.java:143)
        at com.networknt.schema.JsonSchemaFactory.getSchema(JsonSchemaFactory.java:175)
```

Here is part of my schema that specifies the version:

```json
{
    "$id": "schemas/validate.json",
    "$schema": "http://json-schema.org/draft-04/schema",
    "type": "object"

}
```

Any help is appreciated.

**Comment by stevehu** [comment]
@kayvannj Do you have the full schema file so that I can reproduce the issue? Thanks.

**Comment by kayvannj** [comment]
I figured what was causing the issue and it was that the lib is expecting $schema url to end with a `#` which was missing from my schema. I'm not 100% sure if the `#` at the end is part of the spec for json schema, if not, we should make the lib accept the urls with out the ending `#` as well.

**Comment by stevehu** [comment]
It doesn't mention anything regarding to "#"

```
The "$schema" Keyword
The "$schema" keyword is both used as a JSON Schema version identifier and the location of a resource which is itself a JSON Schema, which describes any schema written for this particular version.

The value of this keyword MUST be a URI [RFC3986] (containing a scheme) and this URI MUST be normalized. The current schema MUST be valid against the meta-schema identified by this URI.

If this URI identifies a retrievable resource, that resource SHOULD be of media type "application/schema+json".

The "$schema" keyword SHOULD be used in a root schema. It MUST NOT appear in subschemas.

[CREF2]

Values for this property are defined in other documents and by other parties. JSON Schema implementations SHOULD implement support for current and previous published drafts of JSON Schema vocabularies as deemed reasonable.
```

**Comment by stevehu** [comment]
All examples have the "#" though. This may due to the convention of json-schema.org website. I would recommend following the examples. 

```
http://json-schema.org/draft-07/schema#
```

**Comment by kayvannj** [comment]
yeah, thank you. I'm closing this issue. I have a separate issue that I'll create.
